// Generated by gencpp from file stock_verifier_package/stock_verifier.msg
// DO NOT EDIT!


#ifndef STOCK_VERIFIER_PACKAGE_MESSAGE_STOCK_VERIFIER_H
#define STOCK_VERIFIER_PACKAGE_MESSAGE_STOCK_VERIFIER_H

#include <ros/service_traits.h>


#include <stock_verifier_package/stock_verifierRequest.h>
#include <stock_verifier_package/stock_verifierResponse.h>


namespace stock_verifier_package
{

struct stock_verifier
{

typedef stock_verifierRequest Request;
typedef stock_verifierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stock_verifier
} // namespace stock_verifier_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stock_verifier_package::stock_verifier > {
  static const char* value()
  {
    return "f204c14e57790d0ec7eb4cdddb7dd4f7";
  }

  static const char* value(const ::stock_verifier_package::stock_verifier&) { return value(); }
};

template<>
struct DataType< ::stock_verifier_package::stock_verifier > {
  static const char* value()
  {
    return "stock_verifier_package/stock_verifier";
  }

  static const char* value(const ::stock_verifier_package::stock_verifier&) { return value(); }
};


// service_traits::MD5Sum< ::stock_verifier_package::stock_verifierRequest> should match 
// service_traits::MD5Sum< ::stock_verifier_package::stock_verifier > 
template<>
struct MD5Sum< ::stock_verifier_package::stock_verifierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stock_verifier_package::stock_verifier >::value();
  }
  static const char* value(const ::stock_verifier_package::stock_verifierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stock_verifier_package::stock_verifierRequest> should match 
// service_traits::DataType< ::stock_verifier_package::stock_verifier > 
template<>
struct DataType< ::stock_verifier_package::stock_verifierRequest>
{
  static const char* value()
  {
    return DataType< ::stock_verifier_package::stock_verifier >::value();
  }
  static const char* value(const ::stock_verifier_package::stock_verifierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stock_verifier_package::stock_verifierResponse> should match 
// service_traits::MD5Sum< ::stock_verifier_package::stock_verifier > 
template<>
struct MD5Sum< ::stock_verifier_package::stock_verifierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stock_verifier_package::stock_verifier >::value();
  }
  static const char* value(const ::stock_verifier_package::stock_verifierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stock_verifier_package::stock_verifierResponse> should match 
// service_traits::DataType< ::stock_verifier_package::stock_verifier > 
template<>
struct DataType< ::stock_verifier_package::stock_verifierResponse>
{
  static const char* value()
  {
    return DataType< ::stock_verifier_package::stock_verifier >::value();
  }
  static const char* value(const ::stock_verifier_package::stock_verifierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STOCK_VERIFIER_PACKAGE_MESSAGE_STOCK_VERIFIER_H
