// Generated by gencpp from file stock_verifier_package/stock_verifierRequest.msg
// DO NOT EDIT!


#ifndef STOCK_VERIFIER_PACKAGE_MESSAGE_STOCK_VERIFIERREQUEST_H
#define STOCK_VERIFIER_PACKAGE_MESSAGE_STOCK_VERIFIERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stock_verifier_package
{
template <class ContainerAllocator>
struct stock_verifierRequest_
{
  typedef stock_verifierRequest_<ContainerAllocator> Type;

  stock_verifierRequest_()
    : a(0)  {
    }
  stock_verifierRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
    }



   typedef int64_t _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stock_verifierRequest_

typedef ::stock_verifier_package::stock_verifierRequest_<std::allocator<void> > stock_verifierRequest;

typedef boost::shared_ptr< ::stock_verifier_package::stock_verifierRequest > stock_verifierRequestPtr;
typedef boost::shared_ptr< ::stock_verifier_package::stock_verifierRequest const> stock_verifierRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace stock_verifier_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stock_verifier_package/stock_verifierRequest";
  }

  static const char* value(const ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n\
";
  }

  static const char* value(const ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct stock_verifierRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stock_verifier_package::stock_verifierRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCK_VERIFIER_PACKAGE_MESSAGE_STOCK_VERIFIERREQUEST_H
